### PR TITLE
Fixes for scheduled notifications

### PR DESCRIPTION
**Pull request by adintegra**
Fixed a bug for scheduled push in getPayload() and aligned the MIME type as per Urban Airship's documentation.

### CODE REVIEW

**Comment by pdxmele** [comment]
Thank you for your contribution! Please sign our contribution agreement and we'll take a look shortly afterwards: http://docs.urbanairship.com/contribution-agreement.html

**Comment by rimhoffd** [comment]
👍

**Comment by devinsmythe** [comment]
@adintegra what bug are you running into with getPayload()?  
Can you reach out to support@urbanairship.com with your implementation along with error logs etc you are getting?

**Comment by pdxmele** [comment]
Please contact support @ https://support.urbanairship.com/ if you're still running into problems with this.

**Pull request closed without merging**
