### PR TITLE
adds named user support

### PR DESCRIPTION
**Pull request by jonbest**
adds ability to push notifications by named users. 

usage:
```php
<?php
// ...
$airship->push()
    ->setAudience(P\namedUser('user-1234'))
    ->setNotification(P\notification('hello world'))
    ->setDeviceTypes(array('ios', 'android'))
    ->send();
// ...
?>
```
Note: device type cannot be set to P\all currently due to lack of named user support for windows. it must be an `array` containing one of or both `'ios'` and `'android'`

### CODE REVIEW

**Comment by keepitsimple** [comment]
Hello UrbanAirship! 

For me it shows big disrespect from Urban Airship management  to they clients if nobody from the PHP library team did merge **already implemented fix** for 11 months!

Sorry, but it's a shame

**Comment by pdxmele** [comment]
Hi there,

Sorry about the delay. We don't have engineers dedicated to this library (hence the wait), but we'll be working on some updates in the coming months. Please feel free to fork the repo and use your own version as you'd like in the meantime. Thank you again for your patience.

@jonbest Thank you for your contribution! Please sign our contribution agreement and we'll take a look shortly afterwards: http://docs.urbanairship.com/contribution-agreement.html

**Comment by keepitsimple** [comment]
I appreciate your response. 
It will be really great if so important feature will be integrated soon into official library. 
Thank you.

**Comment by jonbest** [comment]
@pdxmele glad to help! i completed the contribution agreement; let me know if there are any issues with it

**Comment by pdxmele** [comment]
Thanks @jonbest !

**Comment by strusewych** [comment]
Is there any intention to merge this PR?

**Comment by devinsmythe** [comment]
There will be a new release out soon that will include named users.

**Pull request closed without merging**
